[workspace]
members = [
	".",
	"python",
	"wasm",
]

[workspace.package]
edition = "2024"
license = "BSD-3-Clause"
authors = ["MolCrafts"]
repository = "https://github.com/MolCrafts/molcore"
homepage = "https://github.com/MolCrafts/molcore"

[package]
name = "molcore"
version = "0.1.0"
edition = "2024"
authors = ["MolCrafts"]
description = "MolCrafts molecular modeling core library (molcore)"
homepage = "https://github.com/MolCrafts/molcore"
repository = "https://github.com/MolCrafts/molcore"
license = "BSD-3-Clause"

[features]
# Slow and comprehensive integration tests (requires test data to be downloaded)
slow-tests = []

[dependencies]
flate2 = { version = "1.0", features = ["rust_backend" ] }
winnow = { version = "0.7.13" }