[package]
name = "molomni"
version = "0.1.0"
edition = "2024"
authors = ["MolCrafts"]
description = "MolCrafts molecular modeling core library (molomni)"
homepage = "https://github.com/MolCrafts/molomni"
repository = "https://github.com/MolCrafts/molomni"
license = "BSD-3-Clause"

[dependencies]
polars = { version = "x", features = ["lazy"] }