[workspace]
members = [".", "python", "wasm"]

[workspace.package]
edition = "2024"
license = "BSD-3-Clause"
authors = ["MolCrafts"]
repository = "https://github.com/MolCrafts/molcore"
homepage = "https://github.com/MolCrafts/molcore"

[package]
name = "molcore"
version = "0.1.0"
edition = "2024"
authors = ["MolCrafts"]
description = "MolCrafts molecular modeling core library (molcore)"
homepage = "https://github.com/MolCrafts/molcore"
repository = "https://github.com/MolCrafts/molcore"
license = "BSD-3-Clause"

[features]
slow-tests = []
blas = ["ndarray-linalg"]

[dependencies]
ndarray = "0.16"
rustworkx-core = "0.17"
winnow = "0.7.13"
flate2 = { version = "1.0", features = ["rust_backend"] }
rayon = { version = "1.11", optional = true, default-features = false }
ndarray-linalg = { version = "0.16", optional = true, default-features = true }