[package]
name = "molomni-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords = ["computational", "chemistry", "molecular", "science"]
categories = ["science", "data-structures"]

[lib]
name = "molomni"

[dependencies]
