[package]
name = "molcore"
version = "0.1.0"
edition = "2024"
authors = ["MolCrafts"]
description = "Molcrafts molecular modeling core library"
readme = "README.md"
homepage = "https://github.com/Roy-Kid/molcore"
repository = "https://github.com/Roy-Kid/molcore"
license = "BSD-3-Clause"
keywords = ["computational", "chemistry", "molecular", "science"]
categories = ["science", "data-structures"]

[dependencies]
